src/index.tsx
I prefer using `static contextType` over render props in class components, personally. So we should export the raw context.
```js
import { SafeAreaContext } from 'react-native-safe-area-context';
class SomeComponent extends React.Component {
static contextType = SafeAreaContext;
render() {
return <Text>{JSON.stringify(this.context)}</Text>
}
}
```
=> Export SafeAreaContext for use with contextType

android/build.gradle
`getExtOrDefault` in `build.gradle` fails build with exception when property is not specified in root project. And default value is never used.
`project.ext.get(name)` throws `UnknownPropertyException` if the extension does not have a property according to [documentation](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.ExtraPropertiesExtension.html#org.gradle.api.plugins.ExtraPropertiesExtension:get(java.lang.String)).
Use `project.ext.has(name)` method to check if the extension has a property and then return its value using `project.ext.get(name)`.
- Run `example` project
- Check if build is fine and uses version from root project
- Remove `compileSdkVersion` in root project
- Check if build is fine and uses default version
=> Fix failed build if sdkVersions are not specified in Android root project

android/.npmignore, ios/.npmignore, package.json
Fix #24 by positively identifying directories + files we want in package.json files section, then using npmignore files to ignore unwanted platform files
These is the same package.json::files +  .npmignore combo style we use in react-native-device-info to make better packages, courtesy of @Friederbluemle https://github.com/react-native-community/react-native-device-info/pull/872
```
(base) mike@kunashir:~/work/react-random/react-native-device-info (master) % cp ios/.npmignore ../react-native-safe-area-context/ios/
(base) mike@kunashir:~/work/react-random/react-native-device-info (master) % cp android/.npmignore ../react-native-safe-area-context/android/
```
=> fix(build): npmignore unwanted platform-specific files

README.md
Reading the docs, I found necessary add some code to difference the existence packages from new package added in android manual linking.
I added ellipsis to demostrate for developer user the area to insert your code, like already used in implementations.
=> Added ellipsis in methods calls on android linking

README.md
Linking with `react-native link` is no longer necessary in RN >= 0.60.
=> Docs: linking in RN 0.60 is automatic

ios/SafeAreaView/RNCSafeAreaView.m
On iOS, nested safe area views do not get their padding applied. I think this is because `setSafeAreaInsets` overrides the existing selector - but we don't need to do that as we have `safeAreaInsetsDidChange`
This simplifies the logic a bit too
Verify it SAVs work when nested - I did this in my personal project
=> Fix nested SafeAreaViews

ios/SafeAreaView/RNCSafeAreaViewLocalData.h
I've been updating this library in Expo for SDK38 and then the build failed due to `Unknown type name 'UIEdgeInsets'` error.
Expo client with vendored code from v2.0.1 including this change compiled successfully. It cannot break anything 😄
=> Add missing UIKit import

src/SafeAreaContext.tsx
On Android when keyboard is opened useSafeAreaInsets dispatch a re-render but the insets haven't  changed.
This fix prevent unnecessary re-renders.
=> Fix set insets if the new insets changed

src/SafeAreaContext.tsx
The forward ref is necessary in case the component underneath uses it.
This PR is related to the issue #108 
I added the forwardRef to the withSafeAreaInsets, I'm not very experienced with typescript, I tried to implement the correct typing to allow to forward the ref, It should work even if you the component does not pass a ref, ref can be null, I think this typing allows it but I'm not really sure.
I had trouble running the example, as it run but entered in a loop and crashed, even before adding the forwardRef.
I did test It with the patch I included in the issue tracker before.
=> Added forward Ref to withSafeAreaInsets

src/SafeAreaView.tsx
If `style` prop is undefined, `StyleSheet.flatten` will also return undefined. The code will dump consequently when it tries to destructure `flatStyle`:
https://github.com/th3rdwave/react-native-safe-area-context/blob/fc98fb3725daf60d568b10bcc2c291c52c06d91e/src/SafeAreaView.tsx#L44-L52
This is what I observed when using `react-native-web`.
The following code should work with this PR:
```jsx
<SafeAreaView>
<Text>test</Text>
</SafeAreaView>
```
=> fix: use default empty style

README.md
I was hoping to update the README to include the insight from [this comment](https://github.com/th3rdwave/react-native-safe-area-context/issues/31#issuecomment-601074087). My coworkers and I spent some time trying to figure out how to properly render a component under a `SafeAreaProvider` using `enzyme`. One engineer found [this comment](https://github.com/react-navigation/react-native-safe-area-view/issues/104#issuecomment-597789305) which is copied by the above comment. I figure if there are several people independently looking for answers to this across packages it may be worth calling it out in the documentation.
But of course, it may _not_ be worth including documentation for a potential edge case bound to a specific testing utility! And I do realize that [this …
=> Include tips for testing with enzyme in README

android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewManager.java
Because SafeAreaViewManager extends `ViewGroupManager`, some props on `<View>` that are handled by [`ReactViewManager`](https://github.com/facebook/react-native/blob/v0.63.2/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.java) and other classes that extend `ViewGroupManager` aren't handled. Notably, this includes `pointerEvents`, which can be used to make the SafeAreaView ignore taps when it's used as an overlay.
I installed a [branch](https://github.com/hsource/react-native-safe-area-context/releases/tag/v3.1.1-wanderlog.1) containing the fix to my own app.
To test this, create an instance of `<SafeAreaView style={{ flex: 1 }} pointerEvents="box-none">` that overlays a button or map. The button should be tappable and the map should be pannable.
| Before | After …
=> Fix pointerEvents, other props on SafeAreaView not working on Android

src/CompatNativeSafeAreaProvider.tsx, src/useWindowDimensions.tsx
As requested by @janicduplessis  [in this comment](https://github.com/th3rdwave/react-native-safe-area-context/issues/133#issuecomment-676584480).
@janicduplessis I am having trouble running the example app on iOS. On startup I face error `Operator 'abs' not found`, linking to `node_modules/react-native-reanimated/ios/Nodes/REAOperatorNode.m#L94`. Does current `master` work properly for you?
I will check Android in a moment, but still opening as a draft since I am unable to verify on iOS.
=> Use own copy of useWindowDimensions

react-native-safe-area-context.podspec
Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. This change requires React Native 0.60.2 or newer. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Use this branch to install with an app running on Xcode 12.
=> fix: Xcode 12 compatibility

src/SafeAreaContext.tsx
Set displayName for contexts so that they rendered with proper name in React Devtools, thus improve developer experience.
When you see tree in React Devtools, it'll show SafeAreaInsetsContext.Provider and SafeAreaFrameContext.Provider  instead of just mere Context.Provider.
=> set displayName in contexts

ios/SafeAreaView.xcodeproj/project.pbxproj
Adding all .h and .m files to the Xcode project to ensure that all files are available and linked for non-autolinking scenarios (RN <= 0.59).
This should fix #158.
I had an older RN project that was still on RN 0.59.10. When adding this project and linking (manually via `react-native link`), the build failed. I noticed that not every file was included in the project. When manually fixing this, my build succeeded.
As mentioned in the summary, I had a RN project on version 0.59.10. The build failed until I manually added the rest of the `.h`. and `.m` files to the project. This makes the same change that fixed my build.
Perhaps there should be a CI build of a RN project of version 0.59 if it is claimed to be supported?
=> RN <= 0.59 Linking

README.md
Add documentation note about #169
=> #169 - Note: RN < 0.60 requires 3.1.9 release.

android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaUtils.java
Fixes #176
This may not be the ideal fix... I'm open to other options. Perhaps it should consider the scenario of the view extending beyond the window boundaries to simply be "invalid" and return `null`?? Perhaps there's something I'm missing in the intended behavior here?
The problem is described in detail in #176. The short version is that, during rotation on Android there's a transitional phase where the window's dimensions have been updated according to the rotation but the view's have not, so the view might extend beyond the height or width of the window. The current calculations in `getSafeAreaInsets` were adding this difference in dimensions to the normal insets and returning extremely large insets.
I have _not_ tested with a device/app that actually renders under a cutaway or …
=> If view extends beyond window boundaries, do not add that difference to the insets

android/build.gradle
I noticed a warning that I got in my React Native project after pulling in this library:
```
WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
```
Just wanted to help out and remove `jcenter()` from this project as jcenter is shutting down.
=> Use mavenCentral() since jcenter is shutting down

jest/mock.js
When adding the mock to my Jest setup file following the instructions in the documentation, I get the following error when running my tests:
```error
ReferenceError: React is not defined
at Component (node_modules/react-native-safe-area-context/jest/mock.js:23:5)
at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6016:18)
```
This change makes the tests pass.
=> Fix ReferenceError: React is not defined

ios/SafeAreaView/RNCSafeAreaView.m
When setting edges or mode, currently updateLocalData will be called before invalidateSafeAreaInsets meaning that _currentSafeAreaInsets will be zero. This in turn causes the shadow view to be updated with a padding (or margin) of zero. This in turn sometimes causes a 1 frame flicker (only reproducible on real device, not sim) where the safe area view is zero before being updated with the correct one.
=> Only update local data if provider is present

src/SafeAreaContext.tsx
In response to https://github.com/th3rdwave/react-native-safe-area-context/issues/253, `__DEV__` was recently explicitly defined as a local variable [here](https://github.com/th3rdwave/react-native-safe-area-context/blob/main/src/SafeAreaContext.tsx#L11). That's generally fine, but some of use naive tools like [babel-plugin-transform-define](https://github.com/FormidableLabs/babel-plugin-transform-define) to rewrite globals like `__DEV__` to a constant value when bundling. 
```js
// before babel-plugin-transform-define
const __DEV__ = process.env.NODE_ENV !== 'production';
// after babel-plugin-transform-define (unfortunate)
const false = process.env.NODE_ENV !== 'production';
```
This then leads to errors like:
```
error: node_modules/react-native-safe-area-context/src/SafeAreaContext.tsx …
```
=> Renamed __DEV__ (that's no longer a global) to prevent conflicts with babel-plugin-transform-define

android/build.gradle
When you are building on android using the new architecture, required architecture check is missing. 
Running the command: `react-native run-android  --active-arch-only` will fail if you don't first build for every single arch (`react-native run-android`)
1. Try to run `react-native run-android  --active-arch-only` in a project that implements `react-native-safe-area-context` as a first command and it will failed with the following error:
`fcntl(): Bad file descriptor
/Users/username/Library/Android/sdk/ndk/21.4.7075529/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
Android NDK: Check that /Users/username/XX/source/XX-mob/XX/android/app/build/react-ndk/exported/x86/libfb.so exists or that its path is correct --> As I'm running just for `armeabi-v7a` x86 arch will …
=> Add required architecture only check

react-native-safe-area-context.podspec
Updated the Podspec for iOS so that it supports the latest versions of React Native (`0.69.x`). The dependency needs to be "React-Core" now instead of "React" in order for the iOS build to succeed. Otherwise, there are undefined symbol errors.
Xcode build failed when packaged with React Native `0.69.4`. With this small change, the Xcode build succeeds and the app runs successfully.
=> React Native 0.69.x Compatibility

react-native-safe-area-context.podspec
RCT_NEW_ARCH_ENABLED=0 is not working, sometimes disturb when we enable and disable the new arch
`RCT_NEW_ARCH_ENABLED=1` enable new arch and then try to disable `RCT_NEW_ARCH_ENABLED=0` then Xcode will get an error when it will be building app
=> fix: RCT_NEW_ARCH_ENABLED=0 to disable new arch

android/build.gradle
Currently the Fabric build on 0.71.0 is broken. 
I introduced changes in `android/build.gradle` script that allow the project to compile (I've done the same thing in `react-native-screens` using `patch-package` and it seems to be working just fine).
Resolves #338.
**Please note** that this change drops Fabric support for older versions of React Native (Paper should work just fine), but I believe [it is acceptable](https://github.com/th3rdwave/react-native-safe-area-context#new-architecture-support).
I did not migrate `fabric-example`, but this change is tested in other libs (`react-native-screens`, `react-native-svg`) and compliant to suggestions in:
* [Android's readme in RN repo](https://github.com/facebook/react-native/blob/e108e9ebf1e6c52b6eeffeb6c41f842ad95baa0d/android/README.md)
* …
=> chore: support Fabric on RN 0.71.0

ios/RNCSafeAreaView.m
> [native] Could not locate shadow view with tag #583, this is probably caused by a temporary inconsistency between native views and shadow views
Caused when a view is removed - presumably the shadow view is removed, and we try and update data
I could reliably reproduce it locally, and can confirm the fix works
I can't quite follow the logic here of why we fallback to using the current view when a provider cannot be found. The current view won't emit `RNCSafeAreaDidChange` events - but then I'm not clear why we even saw this bug in the first place.
=> Fix `Could not locate shadow view` errors

src/InitialWindow.native.ts
Fixes #290 
Fixes #255 
The reason is described in #290, it appears that the native module import comes back as `{ default: {} }`.
The fix ensures `getConstants` is only called if it's defined. When mocked, `default` is `{}` and thus `default.getConstants` is `undefined`.
Verified to work in our own projects. Using it via `patch-package`
=> fix(test): _NativeSafeAreaContext.default.getConstants is not a function

src/SafeAreaContext.tsx
I was profiling my App and found that the stackTrace was quite big
Digging into the codebase i found the `withSafeAreaInsets` which renders and extra consumer.
Changed the consumer to the useContext which is the recommended approach according to the react docs and provide 1 less stack and reuse code. 
https://beta.reactjs.org/reference/react/createContext#consumer.
Tested on my app the change and didn't spot any issue. AFAIK, the useContext is equivalent as the consumer so no more impact.
=> refactor: reuse 'useSafeAreaInsets' on withSafeAreaInsets

react-native-safe-area-context.podspec
On Thursday the 30th, Apple Released Xcode 14.3
Xcode 14.3 enforce a version check that React-Native-Safe-Area-View, which supported iOS 11 as minimum version, could not be build anymore.
RCT_NEW_ARCH_ENABLED=1 npx pod-install
build react-native-safe-area-context origin version (4.5.0) on Xcode 14.3
build failure
build react-native-safe-area-context patch version as this commit on Xcode 14.3
build success
=> fix: Cocoapods for Xcode 14.3

ios/RNCSafeAreaViewEdges.h, ios/RNCSafeAreaViewEdges.m
As #204 states, providing an empty array as edges to the SafeAreaView component should result into no edges being set. When the edges prop is omitted, all edges should still be set as default
I've tested this on an iPhone 14 Pro
```Typescript
<SafeAreaView edges={[]} style={{ backgroundColor: 'blue', flex: 1 }}>
<View style={{ backgroundColor: 'red', flex: 1 }} />
</SafeAreaView>
```
| no edges (defaults to all) | edges={['bottom']} | edges={[]} |
|--------|--------|--------|
| ![IMG_3120](https://user-images.githubusercontent.com/60874935/234274620-6bfb83b1-07f7-4a67-ab7d-f824696a9d81.PNG) | ![IMG_3121](https://user-images.githubusercontent.com/60874935/234274612-2344c7a8-a734-4a83-9104-8399b4e77539.PNG) | ![IMG_3119](https://user-images.githubusercontent.com/60874935/234274627-cc06bb26-2 …
=> fix: 🐛 empty array sets no edges

common/cpp/react/renderer/components/safeareacontext/RNCSafeAreaViewState.h
The Geometry.h file is deprecated and will be removed in the next version of React Native.
=> fix:Compatible with version 0.72

src/SafeArea.types.ts, src/SafeAreaView.tsx, src/SafeAreaView.web.tsx
This PR solves the issue #295 by adding the ability for the web's `SafeAreaView` to forward the ref to the underlying `View`.
I run the code by creating a basic Expo app and patching it with my changes.
=> Allow web's SafeAreaView to forward ref to its underlying view

android/build.gradle, android/src/main/AndroidManifest.xml
Resolves #392 
> Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
> Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: 
> https://developer.android.com/studio/build/configure-app-module#set-namespace
More context: https://github.com/react-native-community/discussions-and-proposals/issues/671
>
=> set namespace in build.gradle

package.json
After v4.6.0, the types declaration isn't found. So adjusted the declaration path in package.json to `lib/typescript/src/index.d.ts`
N/A
=> fix(minor): type declaration path in package.json

ios/Fabric/RNCSafeAreaProviderComponentView.mm, ios/RNCSafeAreaProvider.m
When the keyboard shows/hides in pageSheet/formSheet presentation styles, the modal is pushed partially up, so the `y` position changes
=> Update safe area frame when keyboard shows/hides

react-native-safe-area-context.podspec
Fixes an issue when building for tvOS and Fabric enabled.
Fix an issue when building for tvOS and Fabric enabled:
```
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context-tvOS » RNCSafeAreaViewShadowNode.cpp
❌  (ios/Pods/Headers/Public/React-Fabric/react/renderer/components/view/conversions.h:111:39)
109 |     case YGUnitPercent:
110 |       return base.has_value()
> 111 |           ? std::optional<Float>(base.value() * floatFromYogaFloat(value.value))
|                                       ^ 'value' is unavailable: introduced in tvOS 12.0
112 |           : std::optional<Float>();
113 |     case YGUnitAuto:
114 |       return {};
```
https://github.com/react-native-tvos/TVReanimated should build without any need for a patch to this module.
=> Update podspec to tvOS 12.4

src/SafeAreaContext.tsx, src/__tests__/__snapshots__/SafeAreaContext-test.tsx.snap, src/__tests__/__snapshots__/SafeAreaView-test.tsx.snap
I saw some memoization in the provider. It was just partial memoization. I thought to complete the memoization. I'm not sure of the implications memoization had, but partial memoization defeats the purpose. Related: #426
The first commit to use the setState callbacks that one I'm very confident about. Memoizing the whole component in the third commit, and memozing style, I'm not sure if any benefits. But it completes the memoizing.
Old tests still stand.
=> Complete the partial memoization of provider

src/SafeAreaContext.tsx
`SafeAreaContext.ts` contains an import for `ViewProps` that does not meet the TypeScript v5 `verbatimModuleSyntax` rule. It is now imported as `type`.
These changes do not affect testing.
=> chore: resolve ViewProps type import

android/build.gradle
Upcoming react-native 0.73+ includes android gradle plugin 8+ which needs namespace in build.gradle but also needs buildFeatures.buildConfig enabled as well
It is not sufficient to enable this at the top-level app build.gradle, specific modules that use it (such as those that implement new architecture, it seems) must also enable it at the module level
This change was necessary and is in-use in my work app via patch-package as I work through android-gradle-plugin 8+ issues in prep for react-native 0.73 launching for everyone
It is similar to changes I needed to do as react-native-firebase maintainer --> https://github.com/invertase/react-native-firebase/commit/b52d0ce6723c077190618641ce0f33ced9fd4090
With apologies, you have to alter an app that integrates this module to use android …
=> fix(android): enable buildFeatures.buildConfig for android gradle plugin 8+

common/cpp/react/renderer/components/safeareacontext/RNCSafeAreaViewComponentDescriptor.h, common/cpp/react/renderer/components/safeareacontext/RNCSafeAreaViewShadowNode.cpp
Fixed issues causing build failure for android on React Native 0.73.0-rc.4
=> React Native 0.73.0 Support

src/SafeAreaContext.tsx
On web, we get the warning `StyleSheet.compose(a, b) is deprecated; use array syntax, i.e., [a,b].` because apparently this API is deprecated.
=> chore: remove deprecated web API

android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt, android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaView.kt, android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewEdges.kt, android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewLocalData.kt, android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewManager.kt
closes #439 
FabricStateViewManager is deprecated in RN core and it should be migrated just to direct usage of StateWrapper
(it should be safe to use it even with older versions of RN)
- go to `example` folder
- run the packager with `yarn start`
- build the app with `yarn android`
=> fix(#439): remove deprecated FabricViewStateManager class usage

react-native-safe-area-context.podspec
This PR adds visionOS support
1. Init a new visionOS app (using v0.73.3) as safe-area is not working properly on nightly
2. Add `safe-area` from commit 
Related PR: https://github.com/software-mansion/react-native-screens/pull/2025
=> feat: add visionOS support

.github/workflows/android.yml, android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt, android/src/main/jni/CMakeLists.txt, common/cpp/react/renderer/components/safeareacontext/RNCSafeAreaViewShadowNode.cpp
This PR aligns the code with newest version of `yoga` in RN `0.74.0-rc.0`.  Made with huge help from @piaskowyk
=> fix: fixes for new arch on RN 74

src/specs/NativeSafeAreaProvider.ts
Library is currently failing to work on 0.74.0-RC2 due to the library accidentally (?) specifying a paper event name for the `onInsetsChange` event.
The logic in core has changed here: https://github.com/facebook/react-native/commit/76613ec4cd0379649a1cca9c0079b8e6bcdc2663
As the paper event name is not used at all in native code, it's safe to remove entirely.
| Before | After |
| ------ | ----- |
| ![Screenshot_1709911266](https://github.com/th3rdwave/react-native-safe-area-context/assets/3001957/bf85690e-54ba-4bd0-83da-4940532c5d90) | ![Screenshot_1709911093](https://github.com/th3rdwave/react-native-safe-area-context/assets/3001957/8f2e56c0-d95d-4341-9740-e53192154872) |
=> Do not specify paperName for event `onInsetsChanged`

android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt
PR adding check for arch to decide if module is turbomodule since `TurboModule::class.java.isAssignableFrom(moduleClass)` should not be used anymore. It works since the behavior has been restored: https://github.com/facebook/react-native/issues/43213 but I think it is better to be prepared if it would be changed somewhere in the future.
=> fix: check arch to decide if module is turbomodule

android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt
It's possible for the `getInitialWindowMetrics` method to return `null`, which can cause crashes if we force cast it to `Any`. I faced issues with reloading the app, resulting in errors:
```
ERROR  Error: Exception in HostObject::get for prop 'RNCSafeAreaContext': java.lang.NullPointerException: null cannot be cast to non-null type kotlin.Any, js engine: hermes
```
I'm unsure of the expected behavior when `getInitialWindowMetrics` returns null, but the current exception doesn't provide enough information.
- Tested in expo app ✅
=> Prevent from crashing with null cannot be cast to non-null type `kotlin.Any`

ios/RNCSafeAreaProvider.m
Added run recalculation for safe_area when window did become visible
We found missed scenario when we have to run recalculation for safe_area. In case we open before native modal and then   put our app into background mode. After restore it from background and close this modal we see old values for safe_area. We need to run recalculation to cover this scenario.
Native modal partially cover screen and in this case safe_area is reduced a little bit by iOS.
=> fix: added run recalculation for safe_area when window did become visible

src/index.tsx
- Add support for React Server Components.
- This is very basic support which bails everything out of being run on the server.
- We can circle back when it's easier to test, and make more of the module run server-side.
- I tested against this branch https://github.com/expo/expo/pull/29404
=> feat: add React Server Component support

android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewShadowNode.kt
PR adding compatibility for RN `0.75.0-rc.2`. Since `Dynamic` class has been migrated to Kotlin: https://github.com/facebook/react-native/blob/e320ab47cf855f2e5de74ea448ec292cf0bbb29a/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/Dynamic.kt, the name of function to use is strictly `getType`. It is compatible with previous versions so should be safe to just merge.
=> fix: use kotlin compatible getType

android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewShadowNode.kt
Reverts th3rdwave/react-native-safe-area-context#507 since in the newest RCs we decided to drop the `getType` syntax in favor of the old one, meaning this is no longer necessary.
=> Revert "fix: use kotlin compatible getType"

src/SafeAreaContext.tsx
Due to changes to forwardRef render function with @types/react 18.3.5, `withSafeAreaInsets` was throwing TS error.
```typescript
+ render: ForwardRefRenderFunction<T, PropsWithoutRef<P>>,
- render: ForwardRefRenderFunction<T, P>,
``` 
Closes #526 
Not affected.
Tested on =18.3.5 and <= 18.3.4
=> fix: ts error due to react types forwardRef changes

README.md, jest/mock.tsx
Use `jest.fn` on `useSafeAreaInsets` and `useSafeAreaFrame` to allow the use of Mock Functions method as shown below:
```js
import {useSafeAreaInsets} from 'react-native-safe-area-context';
const mockedUseSafeAreaInsets = jest.mocked(useSafeAreaInsets);
mockedUseSafeAreaInsets.mockImplementationOnce()
```
Add a few lines to describe how to parse the mock file using jest config `transformIgnorePatterns`
```js
transformIgnorePatterns: [
'node_modules/(?!((jest-)?react-native|@react-native(-community)?|react-native-safe-area-context)/)',
];
```
Tested linking my react-native-safe-are-context fork as the dependency on my project:
`"react-native-safe-area-context": "git+https://github.com/LucasGarcez/react-native-safe-area-context.git#chore-improve-build-in-mock"`
=>  Extends mock capabilities and doc how to enable Babel parsing

android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt
This is required for RN 0.77 apparently. TurboReactPackage is deprecated on new arch. No idea why.
I am not sure about backwards compatibility either, sorry.
Feel free to close this PR if this isn't backwards compatible.
=> feat: Use `BaseReactPackage` instead of `TurboReactPackage`

android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextPackage.kt
As the comment explains, that parameter can now be dropped.
related: https://github.com/facebook/react-native/pull/39459
Built locally with this change.
=> refactor: remove deprecated ReactModuleInfo parameter

android/src/paper/java/com/facebook/react/viewmanagers/RNCSafeAreaProviderManagerDelegate.java, android/src/paper/java/com/facebook/react/viewmanagers/RNCSafeAreaViewManagerDelegate.java
Hey, I'm adding support for RN 0.77 in `react-native-screens` https://github.com/software-mansion/react-native-screens/pull/2581 and I stumbled on issue with RNSAC.
Basically `BaseViewManagerInterface` [has been removed from `react-native`](https://github.com/facebook/react-native/pull/46809) 
and view manager interfaces & delegates shipped for old arch purposes are no longer valid with 0.77. [The PR](https://github.com/facebook/react-native/pull/46809) claims
that this change should be backward compatible with older RN versions for old architecture.
I've included the patch I'm using in `react-native-screens` for `react-native-safe-area-context` to make my test project build. 
Please note that some more changes might be required for full compatibility with 0.77. 
I'm using this patch in …
=> feat: support for RN 0.77 & old architecture

package.json
```[Codegen] [DEPRECATED] react-native-safe-area-context should add the 'ios.componentProvider' property in their codegenConfig```
See: https://x.com/o_kwasniewski/status/1876960622832697391
RNTA works as expected - haven't noticed any regressions
=> feat: add component provider field for codegen

android/src/main/jni/CMakeLists.txt
Following https://github.com/software-mansion/react-native-screens/pull/2707
Variable names prefixed with `$` are heavily utilised in codegened code. This leads to a wall of warnings popping up during every Android build. This PR aims to suppress these warnings.
☝🏻 and that is not all...
Just build Fabric + Android with this change.
=> chore: suppress `-Wdollar-in-identifier-extension` compiler warning

ios/Fabric/RNCSafeAreaProviderComponentView.h, ios/Fabric/RNCSafeAreaProviderComponentView.mm, ios/Fabric/RNCSafeAreaViewComponentView.h, ios/Fabric/RNCSafeAreaViewComponentView.mm, ios/RNCSafeAreaUtils.h
Follow up of https://github.com/AppAndFlow/react-native-safe-area-context/pull/513
While building BareExpo for macOS I noticed that macOS builds are broken when using the new arch. This PR added the necessary platform checks to fix it 
Manually added macOS to the sample app so I could test it manually.
=> feat: add new arch support to macos

android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaViewManager.kt
Release of React Native 0.79 broke Android builds that resulted in an error:
```sh
Exception thrown when executing UIFrameGuarded
Attempt to invoke interface method 'void com.facebook.react.uimanager.ViewManagerDelegate.setProperty(android.view.View, java.lang.String, java.lang.Object)' on a null object reference
```
Tested on React Native 0.76.1 example and React Native 0.79.0
Closes https://github.com/AppAndFlow/react-native-safe-area-context/issues/607
- Build example project
- Build on project using React Native 0.79
=> chore(android): support react-native 0.79.0

ios/Fabric/RNCSafeAreaProviderComponentView.mm
…
Currently, RNCSafeAreaProviderComponentView is a fabric view. Fabric view using a reusable for views.
We already had `prepareForRecycle` to clean up the state of view when it was removed from the superview.
But we still have 2 things that can affect the state. 
The first one is the notification center. We have not removed it. Then `invalidateSafeAreaInsets` still get called when other places show the keyboard. It will lead to `_initialInsetsSent` being true, and our lib will not emit an event to js. (We have a return)
The second, UIKit still calls `invalidateSafeAreaInsets` when the keyboard shows. So we need a guard to prevent it affect our logic.
We have a problem SafeAreaProvider empty children since `insets` is null, caused by other brownfield screen shows keyboard
=> Prevent invalidateSafeAreaInsets get call when RNCSafeAreaProviderComponentView still in the fabric view pool

docs/docs/api/safe-area-listener.mdx, example/src/App.tsx, example/src/HooksExample.tsx, example/src/ListenerExample.tsx, example/src/components/Card.tsx, src/SafeAreaContext.tsx
This lets consumers get the insets and frame without using the hooks.
So it's possible to minimize re-renders by controlling when state needs
to be updated.
Run the example app and see the insets and frame in the insets example.
=> feat: add a SafeAreaListener component

common/cpp/react/renderer/components/safeareacontext/RNCSafeAreaViewShadowNode.h
Not sure why you folks are setting the `ShadowNodeTraits::Trait::DirtyYogaNode` trait on the SafeAreaView Shadow Node (is it a copy form the core one?).
This trait is going away in core in 0.81.
I'm actually re-adding it to reduce the blast radius of this breaking change, but still it would be worth to clean this up.
Fixes https://github.com/AppAndFlow/react-native-safe-area-context/issues/645
=> [RN 0.81] Do not set the `ShadowNodeTraits::Trait::DirtyYogaNode`
